Create user interface for managing bookings
hatchways/team-bamboo pull request #49
Opened 2022-01-18 03:38 UTC by michael-levitski

Closes  #19

### What this PR does (required):
- list PR functionality here

### Screenshot
![Screenshot 2022-01-17 190630](https://user-images.githubusercontent.com/66583830/149866100-a6d56b4f-d118-433d-ad37-3231489acbe0.png)

### Any information needed to test this feature (required):
- uses `calendar` npm package
- visit url path `/bookings`

2022-01-18 19:05 UTC, ezeilo-su requested changes
Good work on this one. But a few comments to have a look at.

2022-01-18 19:05 UTC, sundayezeilo commented on client/src/components/Calendar/CalendarBody.tsx
> +  //if the date falls outside of the current month
Please remove these comments

2022-01-18 19:05 UTC, ezeilo-su commented on client/src/components/Calendar/CalendarDay.tsx
> +    <div style={{ width: '50px', textAlign: 'center', margin: '5px 0px' }}>
Please use the MUI `Box` components for `div`

2022-01-18 19:05 UTC, ezeilo-su commented on client/src/pages/Bookings/Bookings.tsx
> +console.log(filteredBookings.map((b) => b.start));
Please watch for unnecessary logs to the console. Going forward, we should be cleaning up our logs done during development. Thanks!

2022-01-18 19:05 UTC, ezeilo-su commented on client/src/pages/Bookings/Bookings.tsx
> +console.log(highlightedDates);
The same comment for console.log

2022-01-18 20:31 UTC, rajivtitus commented on client/src/components/BookingList/Booking.tsx
> +    <Card variant="outlined" sx={{ padding: '0px 10px 10px 10px', margin: '10px 0px' }}>
👍🏽

2022-01-18 20:32 UTC, rajivtitus commented on client/src/components/BookingList/Booking.tsx
> +  booking: IBooking;
```suggestion
  booking: Booking;
```
We don't need to prefix our interfaces with 'I' in JS. Ditto where applicable!

2022-01-18 20:34 UTC, rajivtitus commented on client/src/components/BookingList/Booking.tsx
> +    <Card variant="outlined" sx={{ padding: '0px 10px 10px 10px', margin: '10px 0px' }}>
```suggestion
    <Card variant="outlined" sx={{ padding: '0px 10px 10px 10px', margin: '10px 0px' }}>
      <CardContent>
```
Nit: We can wrap the contents with the `CardContent` component to stay consistent with MUI semantics 😄

2022-01-18 20:34 UTC, rajivtitus commented on client/src/components/BookingList/BookingList.tsx
> +  bookings: IBooking[];
```suggestion
  bookings: Booking[];
```

2022-01-18 20:38 UTC, rajivtitus commented on client/src/components/BookingList/BookingList.tsx
> +        <Booking key={b.start.getTime()} booking={b} />
Let's make sure we use unique indexes as keys in React. If two pending bookings have the same start time we will no longer have unique keys for our component

Importance of unique indexes in React: https://betterprogramming.pub/why-react-keys-matter-an-introduction-136b7447cefc

2022-01-18 20:39 UTC, rajivtitus commented on client/src/components/Calendar/CalendarDay.tsx
> +const useStyles = makeStyles((theme: any) => ({
Please avoid using `any` as a type

2022-01-18 20:40 UTC, rajivtitus commented on client/src/components/Calendar/CalendarDay.tsx
> +  const classes = useStyles(calendarDate);
👍🏽

2022-01-18 20:41 UTC, rajivtitus commented on client/src/components/NextBookings/NextBooking.tsx
> +      <Grid container direction="row" justifyContent="space-between" alignItems="flex-end">
Same as comment above about the usage of `CardContent`

2022-01-18 20:41 UTC, rajivtitus commented on client/src/pages/Bookings/Bookings.tsx
> +const inMemoryCurrentBookings: Booking[] = [
👍🏽

2022-01-18 20:42 UTC, rajivtitus commented on client/src/pages/Bookings/Bookings.tsx
> +  useEffect(() => {
Please remove this `useEffect`, we don't need to initialize the socket connection within this component

2022-01-18 20:43 UTC, rajivtitus commented on client/src/pages/Bookings/Bookings.tsx
> +              '::-webkit-scrollbar': {
Suggestion: I think we can move some of these additional styles into a CSS class for increased readability within this component

2022-01-18 20:45 UTC, rajivtitus reviewed
Very good work with this Michael! Just some minor comments for you to address, thanks!

2022-01-19 02:02 UTC, michael-levitski commented on client/src/pages/Bookings/Bookings.tsx
> +});
This change is outdated due to a future commit

2022-01-19 02:05 UTC, michael-levitski commented on client/src/pages/Bookings/Bookings.tsx
> +          <Card className={classes.scrollableCard}>
This change is outdated due to a future commit

2022-01-19 22:02 UTC, rajivtitus approved these changes
Excellent work with those changes 💯

2022-01-20 21:48 UTC, merged